services:
  - type: web
    name: gretchen-north-art
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gretchen_north_art.wsgi:application"
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gretchen-north-art-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
