# Generated by Django 5.2 on 2025-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0004_artwork_quantity_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='height_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='length_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='weight_lb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
